name: Lint and Test Charts

on:
  push:
    branches-ignore:
    - 'master'
  pull_request:
    branches:
    - '**'

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Fetch history
        run: git fetch --prune --unshallow
      
      - name: Create Kubeconfig directories
        run: |
          mkdir ~/.kube
          touch ~/.kube/config

      - name: Run chart-testing (lint)
        id: lint
        uses: helm/chart-testing-action@v1.0.0
        with:
          command: lint
          config: ct-master.yaml

      - name: actions-k3s
        uses: debianmaster/actions-k3s@v1.0.0
        id: k3s
        with:
          version: v1.18.2-k3s1

      - name: Run chart-testing (install)
        uses: helm/chart-testing-action@v1.0.0
        with:
          command: install
          config: ct-master.yaml
          kubeconfig: ${{ steps.k3s.outputs.kubeconfig }}
